const coffeeBean={
    details: [
        { id: 12,
          name: 'Robusta Beans',
          image: 'https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg?cs=srgb&dl=pexels-igor-haritanovich-1695052.jpg&fm=jpg',
          rating: 4.3,
          qualityText: 'Medium Roasted',
          characteristics: 'From Africa',
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {id: 13,
          name: 'Cappuccino Beans',
          image: 'https://www.aeropress.co.uk/cdn/shop/articles/coffee-3392168_1280_480x540_crop_center.jpg?v=1566477301',
          qualityText: 'Medium Roasted',
          characteristics: 'From Africa',
          rating: 4.3,
          smallPrice: 3.1,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        { id:14,
          name: 'Robusta Beans',
          image: 'https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg?cs=srgb&dl=pexels-igor-haritanovich-1695052.jpg&fm=jpg',          
          rating: 4.3,
          qualityText: 'Medium Roasted',
          characteristics: 'From Africa',
          smallPrice: 3.5,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        { id:15,
          name: 'Cappuccino Beans',
          image: 'https://www.aeropress.co.uk/cdn/shop/articles/coffee-3392168_1280_480x540_crop_center.jpg?v=1566477301',
          rating: 4.3,
          qualityText: 'Medium Roasted',
          characteristics: 'From Africa',
          smallPrice: 3.6,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
      ],
    };
    export default coffeeBean;
