const CoffeeData = {
    All: {
        name: 'All',
        details: [{
            id: 0,
            name: 'Cappuccino',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtFATeeELmrETP4ReXT1k7PiwTkH0t6dLFFCPRULqIrsnz8ICrtlqxbBMqJNKVxNmZXag&usqp=CAU',
            rating: 4.7,
            characteristics: 'Classic Cappuccino',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description:
                'Experience the timeless delight of a classic cappuccino with a perfect blend of espresso, steamed milk, and creamy foam.',
        },
        {
            id: 4,
            name: 'Espresso',
            image: 'https://www.thespruceeats.com/thmb/oUxhx54zsjVWfPlrgedJU0MZ-y0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-make-cappuccinos-766116-hero-01-a754d567739b4ee0b209305138ecb996.jpg',
            rating: 4.3,
            characteristics: 'Espresso with milk',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 6,
            name: 'Americano',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtFATeeELmrETP4ReXT1k7PiwTkH0t6dLFFCPRULqIrsnz8ICrtlqxbBMqJNKVxNmZXag&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with foam',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 11,
            name: 'Macchiato',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiPNgnzFO0X_VHPqfKCMZjtA4phu0OAx9H7mR7tJ75X9v-85WcDDOycXMWa0GnkiRC9e8&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with both',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        ]
    },
    Cappuccino: {
        name: 'Cappuccino',
        details: [{
            id: 0,
            name: 'Cappuccino',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtFATeeELmrETP4ReXT1k7PiwTkH0t6dLFFCPRULqIrsnz8ICrtlqxbBMqJNKVxNmZXag&usqp=CAU',
            rating: 4.7,
            characteristics: 'Classic Cappuccino',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description:
                'Experience the timeless delight of a classic cappuccino with a perfect blend of espresso, steamed milk, and creamy foam.',
        },
        {
            id: 1,
            name: 'Cappuccino',
            image: 'https://www.thespruceeats.com/thmb/oUxhx54zsjVWfPlrgedJU0MZ-y0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-make-cappuccinos-766116-hero-01-a754d567739b4ee0b209305138ecb996.jpg',
            rating: 4.6,
            characteristics: 'with Steamed Milk',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'Indulge in a cappuccino with extra steamed milk for a silky and mild flavor.',
        },
        {
            id: 2,
            name: 'Cappuccino',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiPNgnzFO0X_VHPqfKCMZjtA4phu0OAx9H7mR7tJ75X9v-85WcDDOycXMWa0GnkiRC9e8&usqp=CAU',
            rating: 4.5,
            characteristics: 'Cappuccino with Foam',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'Enjoy a cappuccino with an abundance of foam, creating a fluffy and aromatic coffee experience.',
        },
        ]
    },
    Espresso: {
        name: 'Espresso',
        details: [{
            id: 3,
            name: 'Espresso',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtFATeeELmrETP4ReXT1k7PiwTkH0t6dLFFCPRULqIrsnz8ICrtlqxbBMqJNKVxNmZXag&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with foam',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 4,
            name: 'Espresso',
            image: 'https://www.thespruceeats.com/thmb/oUxhx54zsjVWfPlrgedJU0MZ-y0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-make-cappuccinos-766116-hero-01-a754d567739b4ee0b209305138ecb996.jpg',
            rating: 4.3,
            characteristics: 'Espresso with milk',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 5,
            name: 'Espresso',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiPNgnzFO0X_VHPqfKCMZjtA4phu0OAx9H7mR7tJ75X9v-85WcDDOycXMWa0GnkiRC9e8&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with both',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        ]
    },
    Americano: {
        name: 'Americano',
        details: [{
            id: 6,
            name: 'Americano',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtFATeeELmrETP4ReXT1k7PiwTkH0t6dLFFCPRULqIrsnz8ICrtlqxbBMqJNKVxNmZXag&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with foam',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 7,
            name: 'Americano',
            image: 'https://www.thespruceeats.com/thmb/oUxhx54zsjVWfPlrgedJU0MZ-y0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-make-cappuccinos-766116-hero-01-a754d567739b4ee0b209305138ecb996.jpg',
            rating: 4.3,
            characteristics: 'Espresso with milk',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 8,
            name: 'Americano',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiPNgnzFO0X_VHPqfKCMZjtA4phu0OAx9H7mR7tJ75X9v-85WcDDOycXMWa0GnkiRC9e8&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with both',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        ]
    },
    Macchiato: {
        name: 'Macchiato',
        details: [{
            id: 9,
            name: 'Macchiato',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtFATeeELmrETP4ReXT1k7PiwTkH0t6dLFFCPRULqIrsnz8ICrtlqxbBMqJNKVxNmZXag&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with foam',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 10,
            name: 'Macchiato',
            image: 'https://www.thespruceeats.com/thmb/oUxhx54zsjVWfPlrgedJU0MZ-y0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-make-cappuccinos-766116-hero-01-a754d567739b4ee0b209305138ecb996.jpg',
            rating: 4.3,
            characteristics: 'Espresso with milk',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
            id: 11,
            name: 'Macchiato',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiPNgnzFO0X_VHPqfKCMZjtA4phu0OAx9H7mR7tJ75X9v-85WcDDOycXMWa0GnkiRC9e8&usqp=CAU',
            rating: 4.3,
            characteristics: 'Espresso with both',
            smallPrice: 3.2,
            mediumPrice: 3.7,
            largePrice: 4.0,
            qualityText: 'Medium Roasted',
            description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        ]
    },
    categories: [
        { name: 'All' },
        { name: 'Cappuccino' },
        { name: 'Espresso' },
        { name: 'Americano' },
        { name: 'Macchiato' }],

};
export default CoffeeData;


