import constants from "./Constants";

const Data = {
  coffeeCategories: [
    {
      name: 'All',
      details: [{
        name: 'Cappuccino',
        image: constants.svg.coffee1,
        rating: 4.7,
        characteristics: 'Classic Cappuccino',
        price: 5,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description:
          'Experience the timeless delight of a classic cappuccino with a perfect blend of espresso, steamed milk, and creamy foam.',
      },
      {
        name: 'Espresso',
        image: constants.svg.coffee1,
        rating: 4.3,
        characteristics: 'Espresso with both',
        price: 3,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
      {
        name: 'Americano',
        image: constants.svg.coffee1,
        rating: 4.3,
        characteristics: 'Espresso with foam',
        price: 3,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
      {
        name: 'Macchiato',
        image: constants.svg.coffee1,
        rating: 4.3,
        characteristics: 'Espresso with foam',
        price: 3,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
      ]
    },
    {
      name: 'Cappuccino',
      details: [
        {
          name: 'Cappuccino',
          image: constants.svg.coffee1,
          rating: 4.7,
          characteristics: 'Classic Cappuccino',
          price: 5,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description:
            'Experience the timeless delight of a classic cappuccino with a perfect blend of espresso, steamed milk, and creamy foam.',
        },
        {
          name: 'Cappuccino',
          image: constants.svg.coffee2,
          rating: 4.6,
          characteristics: 'with Steamed Milk',
          price: 4,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'Indulge in a cappuccino with extra steamed milk for a silky and mild flavor.',
        },
        {
          name: 'Cappuccino',
          image: constants.svg.coffee1,
          rating: 4.5,
          characteristics: 'Cappuccino with Foam',
          price: 6,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'Enjoy a cappuccino with an abundance of foam, creating a fluffy and aromatic coffee experience.',
        },
      ],
    },
    {
      name: 'Espresso',
      details: [
        {
          name: 'Espresso',
          image: constants.svg.coffee1,
          rating: 4.3,
          characteristics: 'Espresso with foam',
          price: 3.00,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
          name: 'Espresso',
          image: constants.svg.coffee2,
          rating: 4.3,
          characteristics: 'Espresso with milk',
          price: 3.50,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
          name: 'Espresso',
          image: constants.svg.coffee1,
          rating: 4.3,
          characteristics: 'Espresso with both',
          price: 4.20,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
      ],
    },
    {
      name: 'Americano',
      details: [
        {
          name: 'Americano',
          image: constants.svg.coffee1,
          rating: 4.3,
          characteristics: 'Espresso with foam',
          price: 3,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
          name: 'Americano',
          image: constants.svg.coffee2,
          rating: 4.3,
          characteristics: 'Espresso with milk',
          price: 3,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
          name: 'Americano',
          image: constants.svg.coffee1,
          rating: 4.3,
          characteristics: 'Espresso with both',
          price: 3,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
      ],
    },
    {
      name: 'Macchiato',
      details: [
        {
          name: 'Macchiato',
          image: constants.svg.coffee1,
          rating: 4.3,
          characteristics: 'Espresso with foam',
          price: 3,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
          name: 'Macchiato',
          image: constants.svg.coffee2,
          rating: 4.3,
          characteristics: 'Espresso with milk',
          price: 3, // Adjust the price as needed
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
        {
          name: 'Macchiato',
          image: constants.svg.coffee1,
          rating: 4.3,
          characteristics: 'Espresso with both',
          price: 3,
          smallPrice: 3.2,
          mediumPrice: 3.7,
          largePrice: 4.0,
          description: 'A classic single shot espresso for a quick and intense caffeine boost.',
        },
      ],
    },

  ],
  coffeeBean: {
    details: [
      {
        name: 'RobustsBeans',
        image: constants.svg.beans1,
        rating: 4.3,
        characteristics: 'Medium Roasted',
        price: 3.3,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
      {
        name: 'Cappuccino',
        image: constants.svg.beans2,
        rating: 4.3,
        characteristics: 'with steamed milk',
        price: 3.80,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
      {
        name: 'RobustsBeans',
        image: constants.svg.beans1,
        rating: 4.3,
        characteristics: 'Medium Roasted',
        price: 3.10,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
      {
        name: 'Cappuccino',
        image: constants.svg.beans2,
        rating: 4.3,
        characteristics: 'with steamed milk',
        price: 3.20,
        smallPrice: 3.2,
        mediumPrice: 3.7,
        largePrice: 4.0,
        description: 'A classic single shot espresso for a quick and intense caffeine boost.',
      },
    ],

  }
};

export default Data;
